{% set name = "pybrowsers" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybrowsers-{{ version }}.tar.gz
  sha256: c9710d0397217609e4b413f83582e7099ff01a326112a791646fdcd5d6551c26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - python >=3.7
    - pywin32 >=303,<305
    - pyxdg >=0.27,<0.29

test:
  imports:
    - browsers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roniemartinez/browsers
  summary: Python library for detecting and launching browsers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
