{% set name = "pybrowsers" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybrowsers-{{ version }}.tar.gz
  sha256: 5207ba914b0c5166e52a543e1c48eb11c73fd43cab4ec99a92d0752a2310fd9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pywin32 >=303,<309
    - pyxdg >=0.27,<0.29

test:
  imports:
    - browsers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/roniemartinez/browsers
  summary: Python library for detecting and launching browsers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
