{% set name = "pybrowsers" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybrowsers-{{ version }}.tar.gz
  sha256: 2ddecc42b1d892db3d167df15744fcc7c13b9856acc46d014a2824e3981c8492

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - python >=3.7
    - pywin32 >=303,<304
    - pyxdg >=0.27,<0.28

test:
  imports:
    - browsers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roniemartinez/browsers
  summary: Python library for detecting and launching browsers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
